### ISSUE TITLE
Fundator: Machine learning Anomaly Detection with AIS in Real Time

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#20]

**Comment by iver56** [comment]
* Meetupen arrangeres hos Fundator, hvor det er plass til kjempemange
* Fundator sponser lokaler, mat og drikke
* En onsdag-torsdag rundt midt-slutten av november

**Comment by sindresf** [comment]
Det blir torsdag 23. november med mindre noe voldsomt skulle skje.
Kommer tilbake med en beskrivelse i midten av neste uke tror jeg.

**Comment by iver56** [comment]
@sindresf Trenger beskrivelse for å annonsere denne snart, så folk rekker å sette av datoen ;) Beskrivelsen trenger ikke å være spesielt lang eller gjennomtenkt. Du får også mulighet til å oppdatere den selv senere.

**Comment by sindresf** [comment]
okey!

Begynn me dette då: 

**MADART: I just want what’s best for the boat off shore.**

Machine learning Anomaly Detection with AIS in Real Time (MADART) is a project that has been going since February, spanning a summer job project with three students and a currently undergoing master thesis at NTNU.

Sindre, from Fundator, will talk us through the project and how the case of the Norwegian coast is a terrible testing ground for clustering, given its natural representation of _Every $£$@”&! way boats can boat and coast can coast!_ Erhmm.. The work needed to make a static algorithm handle diversity. And, how this might just be: the biggest, most over-engineered way possible to color a line on a map.


![2017-11-07 16_00_10-meetup - madart - google dokumenter](https://user-images.githubusercontent.com/2745573/32500137-c571e854-c3d4-11e7-9948-80defef489c7.png)


17:00 M&G w/ F&D

17:15 Talking

23:15 Sindre will go home to get some sleep, and stop talking.

![2017-11-07 16_00_54-meetup - madart - google dokumenter](https://user-images.githubusercontent.com/2745573/32500181-e1870e8e-c3d4-11e7-82af-17f8d9bafb7b.png)

får med Fundator som sponsor sant?

**Comment by iver56** [comment]
Flott :) Vil du at "MADART: I just want what’s best for the boat off shore" skal være tittelen på arrangementet? Eller foretrekker du "Machine learning Anomaly Detection with AIS in Real Time"?

Skal vi annonsere meetupen (så folk får e-post) senere i dag?

Edit: Ja, jeg kan legge inn Fundator som sponsor

**Comment by iver56** [comment]
@sindresf Jeg har oppdatert draft nå: https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/243950552/ (du må være logget inn for å se den)

Vil du se over før jeg annonserer meetupen?

**Comment by sindresf** [comment]
Kjør på! :)

Gå for den mer standard ^^

**Comment by sindresf** [comment]
Needs to be the organizer to view this

**Comment by iver56** [comment]
Du har to forskjellige meetup.com-kontoer tilknyttet Trondheim Machine Learning Meetup. Kan du prøve med den andre?

**Comment by sindresf** [comment]
Bare kjør på ^^

**Comment by iver56** [comment]
Annonsert 👍

**Comment by iver56** [comment]
@sindresf Ønsker du å publisere presentasjonen?

https://github.com/trondheim-machine-learning-meetup/meetups#avholdte-meetups

Eller vil du helst holde den hemmelig?
